version: '3'

services:
  docker-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking_demo
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      backend:
  backend:
    image: booking-demo
    build:
      context: ../cdw_booking
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url":"jdbc:mysql://docker-mysql:3306/booking_demo?jdbcCompliantTruncation=false"
        }'
    depends_on:
      - docker-mysql
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  frontend:
    image: frontend:10.0.0
    volumes:
      - ./default.conf:/usr/share/nginx/html
    depends_on:
      - backend
    build:
      context: ../CDWEB_CLIENT
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      frontend:
volumes:
  mysql-data:

networks:
  backend:
  frontend:
